// Do not edit. This file is machine generated by the Resource DLL Wizard.

library fileSenderProject;

{ITE} {DFMFileType} {fileSender.dfm}
{ITE} {DFMFileType} {u_SplashScreen.dfm}
{ITE} {RCFileType} {Win32\Debug\fileSenderProject_DRC.rc}

{$R 'fileSender.dfm' 'frmMain:TForm'}
{$R 'u_SplashScreen.dfm' 'frmSplashScreen:TForm'}
{$R 'Win32\Debug\fileSenderProject_DRC.res' 'Win32\Debug\fileSenderProject_DRC.rc'}

{$E ENU}

begin
end.
